name: Lint and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: npm install
        run: npm ci
      - name: eslint review
        uses: reviewdog/action-eslint@v1
        with:
          eslint_flags: "./**/*.{tsx,ts,js}"
      - name: Run eslint
        run: npm run lint
      - name: Run jest
        run: npm test
